server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pgmanager?currentSchema=payment_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: payment_schema
  flyway:
    enabled: true
    schemas: payment_schema
    locations: classpath:db/migration
    default-schema: payment_schema

tenant-service:
  url: http://localhost:8083

# Scheduler timezone — IST
spring.task.scheduling.pool.size: 2
